4 product
frontend-park-mail-ru/2024_1_IMAO pull request #15
Opened 2024-05-14 20:20 UTC by AlexeiLDD

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/modules/dynamicPhone.js
> +  // const input = this.#element.querySelector('[type="tel"]');
в этом файле есть несколько мест за закоменченным кодом. + много где отключаете правило no-invalid-this. Предлагаю или переписать так, чтобы правило не надо было отключать либо отключить тогда для всего файла

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/pages/advert/adCreation.js
> +      // if (pos < 3) event.preventDefault();
закоменченый код давайте уберем

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/pages/cart/cart.js
> +      if (Number(quantity.innerHTML) == 0) {
строгое сравнение давайте делать

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/pages/main/main.js
> +    apiRoute.searchParams.append('count', 20);
20 лучше в константу

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/pages/merchantsPage/merchantsPage.js
> +        document.title += ' ' + 'Пользователь №' + id;
Давайте в этом if тоже конкатинацию через шаблонные строки сделаем

2024-05-15 09:43 UTC, AlexandraSmirnova commented on public/pages/profilePage/profilePage.js
> +      if (position + winHeight >= docHeight - 200 && !this.#isBottomReached) {
что такое 200? тоже лучше в константу с каким-то именем

2024-05-15 13:04 UTC, AlexeiLDD commented on public/components/adCreationForm/adCreationForm.hbs
>          {{!-- <input class="form__input" type="text" id="location" name="city" value="{{city}}" required> --}}
+

2024-05-15 13:25 UTC, AlexeiLDD commented on public/components/adContainer/adContainer.scss
> +      z-index: 10 !important;
Убрал

2024-05-15 13:34 UTC, AlexeiLDD commented on public/components/dropdownWithSearch/dropdownWithSearch.scss
> +.dropdown-with-search--select.wide {
+

2024-05-15 13:37 UTC, AlexeiLDD commented on public/components/editProfileOverlay/editProfileOverlay.js
> +          document.getElementById('imagePreview').style.backgroundImage = 'url(' + e.target.result + ')';
+

2024-05-15 13:38 UTC, AlexeiLDD commented on public/components/imagesUploadPreview/imagesUploadPreview.scss
> +    background-image: url('http://bastianandre.at/giphy.gif');
Хороший вопрос)) Убрал)

2024-05-15 13:50 UTC, AlexeiLDD commented on public/modules/dynamicPhone.js
> +  // const input = this.#element.querySelector('[type="tel"]');
+

2024-05-15 13:51 UTC, AlexeiLDD commented on public/pages/advert/adCreation.js
> +      // if (pos < 3) event.preventDefault();
+

2024-05-15 13:55 UTC, AlexeiLDD commented on public/pages/advert/adCreation.js
> +      if (phone.length == 0) {
+

2024-05-15 14:05 UTC, AlexeiLDD commented on public/pages/main/main.js
> +    apiRoute.searchParams.append('count', 20);
+

2024-05-15 14:05 UTC, AlexeiLDD commented on public/pages/cart/cart.js
> +      if (Number(quantity.innerHTML) == 0) {
+

2024-05-15 14:27 UTC, AlexeiLDD commented on public/pages/profilePage/profilePage.js
> +      if (position + winHeight >= docHeight - 200 && !this.#isBottomReached) {
+

2024-05-15 14:29 UTC, AlexeiLDD commented on public/pages/merchantsPage/merchantsPage.js
> +        document.title += ' ' + 'Пользователь №' + id;
+

2024-05-15 14:44 UTC, AlexeiLDD commented on public/components/editProfileOverlay/editProfileOverlay.js
> +        (keyCode > 47 && keyCode < 58)
+

2024-05-17 15:20 UTC, AlexandraSmirnova requested changes

2024-05-17 15:20 UTC, AlexandraSmirnova commented on public/pages/profilePage/profilePage.js
> +      if (position + winHeight >= docHeight - 200 && !this.#isBottomReached) {
тут не поменяли на константу, в другом файле поменяли

2024-05-17 15:20 UTC, AlexandraSmirnova commented on public/pages/main/main.js
> +// Показывает за сколько пикселей до конца стрвницы начинается подгрузка новых объявлений.
очепятка

2024-05-18 15:31 UTC, AlexandraSmirnova approved these changes

2024-05-18 15:31 UTC, merged